frases_pastilhas_freio = ['Quando eu freio, o carro faz um barulho estranho, como se estivesse rangendo.',
                          'Parece que o pedal do freio está mais baixo do que antes, tenho que apertar mais para o carro parar.',
                          'Meu carro está demorando mais para parar quando eu piso no freio.',
                          'Estou ouvindo um som metálico quando freio, como se algo estivesse raspando.',
                          'Parece que os freios estão meio moles, não estão funcionando como antes.',
                          'O carro treme um pouco quando eu aperto o freio.',
                          'Notei que o freio está fazendo um barulho chiado toda vez que eu uso.',
                          'Preciso usar mais força no pedal para frear, não era assim antes.',
                          'Tem algo errado com os freios, eles não parecem tão confiáveis como antes.',
                          'Ouvi dizer que pode ser as pastilhas de freio, porque está fazendo muito barulho quando eu paro o carro.',
                          'Estou sentindo um cheiro estranho depois de usar os freios.',
                          'Acho que o carro está puxando para um lado quando eu freio.',
                          'Tem um barulho agudo toda vez que piso no freio, parece um apito.',
                          'O freio está dando uns trancos, como se estivesse falhando.',
                          'O pedal do freio está vibrando quando eu tento parar o carro.',
                          'Sinto como se o carro estivesse escorregando um pouco quando eu freio.',
                          'Os freios estão fazendo um barulho como se tivesse areia neles.',
                          'Estou percebendo que o freio está mais sensível, qualquer toque faz o carro parar bruscamente.',
                          'Parece que algo está raspando quando eu piso no freio, como se tivesse uma pedra presa.',
                          'O carro não está parando suavemente, está meio brusco, especialmente em baixa velocidade.',
                          'Estou percebendo que o freio está mais duro, tenho que fazer mais força para parar o carro.',
                          'Parece que o carro está dando uma leve derrapada quando freio em curvas.',
                          'O freio está fazendo um som como se estivesse arranhando alguma coisa.',
                          'Sinto que o carro não para com a mesma eficiência, demora mais para desacelerar.',
                          'Ouço um chiado constante, principalmente quando estou quase parando.',
                          'Parece que tem algo raspando dentro da roda quando piso no freio.',
                          'O pedal do freio está tremendo quando tento parar em uma descida.',
                          'O carro faz um barulho de metal com metal, principalmente quando freio de repente.',
                          'O freio está começando a falhar, às vezes tenho que pisar várias vezes para funcionar.',
                          'Estou notando um barulho de raspagem vindo das rodas toda vez que freio levemente.',
                          'Parece que o freio está mais mole, ele afunda mais do que antes quando piso.',
                          'O carro faz um barulho de atrito toda vez que paro em uma ladeira.',
                          'Notei que o carro dá uma balançada quando freio de leve.',
                          'O pedal do freio está ficando cada vez mais difícil de apertar.',
                          "Estou ouvindo um som estranho, como se fosse um 'toc toc', toda vez que paro.",
                          'Quando piso no freio, parece que tem algo raspando na roda da frente.',
                          'O freio está com uma resposta lenta, demoro mais tempo para parar completamente.',
                          'Sinto uma vibração forte no volante quando aperto o freio.',
                          'Quando piso no freio, parece que o carro está puxando para a direita.',
                          'Estou notando que o carro não está parando de forma suave, ele dá uns trancos.',
                          'O freio está fazendo um barulho contínuo, parece que está raspando em algo.',
                          'Toda vez que freio, ouço um estalo vindo da parte de trás do carro.',
                          'O carro está demorando mais para parar em semáforos, isso não acontecia antes.',
                          'Estou sentindo um cheiro de queimado quando freio muito.',
                          "O carro parece estar 'deslizando' um pouco quando paro rapidamente.",
                          'O pedal do freio está fazendo um som de ar saindo, como se estivesse vazando.',
                          'Toda vez que freio em alta velocidade, sinto o carro tremer.',
                          'Parece que tem algo solto na roda, porque faz um barulho quando freio.',
                          'O carro dá um solavanco quando freio bruscamente.',
                          'Estou notando que os freios fazem um barulho diferente quando estão quentes.']

frases_velas_ignicao = ['O carro está falhando e dando uns trancos quando acelero.',
                        'Parece que o motor está engasgando, especialmente quando eu tento acelerar rápido.',
                        'Estou notando que o carro está demorando mais para pegar quando ligo.',
                        'O motor está fazendo um barulho estranho, como se estivesse batendo.',
                        'Sinto que o carro perdeu potência, ele não está acelerando como antes.',
                        "Parece que o carro está 'engasgando' quando eu tento subir uma ladeira.",
                        'O consumo de combustível aumentou, estou tendo que abastecer com mais frequência.',
                        'O carro está tremendo quando eu paro no semáforo, como se fosse desligar.',
                        'Está saindo um cheiro forte de combustível quando eu tento dar a partida.',
                        'Parece que o motor está funcionando irregularmente, como se estivesse falhando em algumas rotações.',
                        'O carro está dando umas falhadas quando eu tento manter uma velocidade constante.',
                        "O motor parece estar 'piscando', às vezes funciona bem, às vezes não.",
                        'Estou percebendo que o carro está vibrando mais que o normal, principalmente em baixa velocidade.',
                        'O carro não está arrancando direito, fica meio lento no começo.',
                        'Está saindo muita fumaça do escapamento quando eu ligo o carro.',
                        'O motor parece estar fazendo mais barulho do que o normal, como se estivesse mais áspero.',
                        'Sinto que o carro está meio pesado, não responde bem ao acelerador.',
                        'Quando estou em marcha lenta, o motor fica instável, como se fosse morrer.',
                        'O carro está perdendo potência em subidas, parece que não tem força.',
                        'O motor está demorando para responder quando eu piso no acelerador, tem um atraso.',
                        'O carro está engasgando quando tento acelerar de repente.',
                        "Parece que o motor está 'falhando' quando estou na estrada, como se perdesse força de vez em quando.",
                        'O carro está difícil de ligar nas manhãs frias, preciso tentar várias vezes.',
                        'Estou ouvindo uns estalos estranhos vindos do motor quando estou dirigindo.',
                        'Sinto que o carro está tremendo mais ao parar em um semáforo ou sinal de trânsito.',
                        "O motor fica meio 'grosso' quando estou em marcha lenta, não fica funcionando redondo.",
                        'O carro está perdendo velocidade mesmo com o pé no acelerador, parece que não vai.',
                        'Tem horas que o motor faz uns barulhos de estalo quando tento acelerar.',
                        'Estou percebendo um cheiro de gasolina mais forte do que o normal, especialmente quando ligo o carro.',
                        'O carro está puxando mais para o lado quando acelero, parece que o motor não está distribuindo bem a potência.',
                        'O carro está hesitando quando eu tento acelerar, como se não estivesse recebendo combustível suficiente.',
                        'Parece que o motor está pulando quando eu mantenho a velocidade constante, como se estivesse perdendo o ritmo.',
                        'O carro está com dificuldade para manter a marcha lenta, fica oscilando como se fosse apagar.',
                        'Está saindo uma fumaça azulada pelo escapamento, especialmente quando o carro está frio.',
                        'O motor faz um barulho de estalo quando eu ligo o carro, principalmente nas primeiras vezes do dia.',
                        'O carro está vibrando muito quando eu acelero, como se estivesse desbalanceado.',
                        'Quando eu acelero rápido, o carro hesita e depois dá um pulo.',
                        'Sinto que o carro está meio fraco nas acelerações, como se tivesse menos potência.',
                        'O carro está difícil de ligar em dias frios, o motor parece não querer pegar.',
                        'O motor faz um som estranho, como se estivesse batendo metal, quando estou devagar.',
                        "O carro está fazendo um barulho de 'clique' quando eu tento acelerar de repente.",
                        'O carro está demorando para alcançar a velocidade que eu quero, como se estivesse puxando devagar.',
                        "O motor está funcionando de forma irregular, como se estivesse 'engasgando' ao acelerar.",
                        'Está saindo um cheiro de óleo queimado quando o carro está parado.',
                        'O carro está falhando quando eu tento acelerar rápido, como se não estivesse respondendo.',
                        "O motor está tremendo e fazendo um som de 'ronco' quando eu tento manter uma velocidade alta.",
                        'O carro está soltando fumaça preta pelo escapamento, especialmente quando eu acelero.',
                        'Quando estou na estrada, o carro parece perder potência de vez em quando, como se estivesse lutando para manter a velocidade.',
                        'O carro está com dificuldade para subir ladeiras, parece que não tem força suficiente.',
                        "O motor está funcionando de forma irregular, como se estivesse 'piscando' em termos de potência e resposta."]

frases_transmissao = ['O carro está demorando para trocar de marcha, parece que fica preso em uma marcha por mais tempo.',
                      'Estou sentindo uns trancos quando a transmissão muda de marcha, principalmente em baixa velocidade.',
                      'O carro faz um barulho estranho, como se estivesse zumbindo ou assobiando, quando acelero.',
                      'A transmissão está patinando, o motor acelera mas o carro não responde como deveria.',
                      'Estou notando que o carro está perdendo potência quando muda de marcha.',
                      'O câmbio está ficando difícil de engatar, especialmente quando o carro está frio.',
                      'Parece que a marcha não está engatando direito, tenho que tentar várias vezes para funcionar.',
                      'O carro dá uns solavancos quando muda de marcha, como se estivesse pulando.',
                      'A luz de verificação do motor acendeu e acho que é algo relacionado à transmissão.',
                      'Está saindo um cheiro de queimado, especialmente depois de dirigir por um tempo.',
                      'O carro está trocando de marcha sozinho.',
                      'Sinto um solavanco toda vez que muda de marcha.',
                      'A marcha não está entrando direito, fica presa.',
                      'O carro demora para acelerar depois de mudar de marcha.',
                      'Ouço um barulho estranho quando troco de marcha.',
                      'O câmbio está duro, difícil de mexer.',
                      'Parece que a marcha escapa sozinha às vezes.',
                      'O carro está patinando quando tento acelerar.',
                      'Sinto o carro tremer quando muda de marcha.',
                      'O câmbio não está respondendo como deveria.',
                      'O carro dá um tranco quando coloco em drive.',
                      'A marcha está pulando sozinha para neutro.',
                      'O câmbio faz um clique estranho quando troco de marcha.',
                      'O carro está vibrando quando passa de marcha.',
                      'Parece que o carro está hesitando para mudar de marcha.',
                      'O câmbio não está engatando suavemente.',
                      'O carro perde força nas subidas, mesmo com a marcha engatada.',
                      'Está difícil tirar o carro da ré.',
                      'A transmissão está fazendo um som de arranhado.',
                      'O carro fica acelerando sem ganhar velocidade.',
                      'O carro está ficando lento para acelerar depois de uma parada.',
                      'O câmbio faz um barulho metálico quando troco de marcha.',
                      'Estou sentindo uma vibração estranha no volante ao mudar de marcha.',
                      'O carro está hesitando antes de engatar a marcha.',
                      'A transmissão parece estar escorregando quando eu acelero forte.',
                      'O carro está trocando de marcha mais frequentemente do que o normal.',
                      'A marcha está difícil de desengatar quando estou em movimento.',
                      'Sinto um cheiro estranho quando o carro está acelerando.',
                      'O carro está fazendo um som de batida quando muda de marcha.',
                      'O câmbio não está respondendo rapidamente quando eu mudo de marcha.',
                      'A transmissão faz um barulho de arranhado quando o carro está em alta velocidade.',
                      'O carro está pulando ao acelerar em subidas.',
                      'A luz de transmissão está piscando no painel.',
                      'O câmbio faz um som de estalo quando engata a marcha.',
                      'Sinto um solavanco quando o carro tenta acelerar após uma parada.',
                      'A transmissão não está engatando de forma suave durante a troca de marchas.',
                      'O carro está perdendo força ao subir uma ladeira com a marcha engatada.',
                      'O câmbio está travando às vezes quando tento mudar a marcha.',
                      'O carro está emitindo um som de ruído quando a marcha está engatada.',
                      'A marcha não está trocando corretamente, fica oscilando entre as marchas.']